export default [
  {
    LABEL: '메인',
    LAYOUT: null,
    PAGE_KEY: null,
    EXTERNAL_LINK: null,
    CHILD: [
      {
        LABEL: '메인',
        LAYOUT: null,
        PAGE_KEY: 'main',
        EXTERNAL_LINK: null,
      },
    ],
  },
  {
    LABEL: '로그인',
    LAYOUT: null,
    PAGE_KEY: null,
    EXTERNAL_LINK: null,
    CHILD: [
      {
        LABEL: '로그인',
        LAYOUT: null,
        PAGE_KEY: 'login_1',
        EXTERNAL_LINK: null,
      },
    ],
  },
  {
    LABEL: '대쉬보드',
    LAYOUT: null,
    PAGE_KEY: null,
    EXTERNAL_LINK: null,
    CHILD: [
      {
        LABEL: '대쉬보드 메인',
        LAYOUT: 'dashboard',
        PAGE_KEY: 'dashboard_1',
        EXTERNAL_LINK: null,
      },
    ],
  },
  {
    LABEL: '퍼블리싱 가이드',
    LAYOUT: null,
    PAGE_KEY: null,
    EXTERNAL_LINK: null,
    CHILD: [
      {
        LABEL: '테스트',
        LAYOUT: null,
        PAGE_KEY: 'test',
        EXTERNAL_LINK: null,
      },
      {
        LABEL: '커스텀 UI',
        LAYOUT: null,
        PAGE_KEY: null,
        EXTERNAL_LINK: null,
        CHILD: [
          {
            LABEL: 'Component',
            LAYOUT: 'example',
            PAGE_KEY: 'common',
            EXTERNAL_LINK: null,
          },
          {
            LABEL: 'Layout',
            LAYOUT: null,
            PAGE_KEY: null,
            EXTERNAL_LINK: null,
            CHILD: [
              {
                LABEL: 'Header',
                LAYOUT: 'example',
                PAGE_KEY: 'header',
                EXTERNAL_LINK: null,
              },
              {
                LABEL: 'Footer',
                LAYOUT: 'example',
                PAGE_KEY: 'footer',
                EXTERNAL_LINK: null,
              },
            ],
          },
          {
            LABEL: 'Form',
            LAYOUT: null,
            PAGE_KEY: null,
            EXTERNAL_LINK: null,
            CHILD: [
              {
                LABEL: 'Text Input',
                LAYOUT: 'example',
                PAGE_KEY: 'textinput',
                EXTERNAL_LINK: null,
              },
              {
                LABEL: 'Select',
                LAYOUT: 'example',
                PAGE_KEY: 'select',
                EXTERNAL_LINK: null,
              },
              {
                LABEL: 'Dropdown',
                LAYOUT: 'example',
                PAGE_KEY: 'dropdown',
                EXTERNAL_LINK: null,
              },
              {
                LABEL: 'Button',
                LAYOUT: 'example',
                PAGE_KEY: 'button',
                EXTERNAL_LINK: null,
              },
              {
                LABEL: '체크박스',
                LAYOUT: 'example',
                PAGE_KEY: 'checkbox',
                EXTERNAL_LINK: null,
              },
              {
                LABEL: '라디오버튼',
                LAYOUT: 'example',
                PAGE_KEY: 'radiobutton',
                EXTERNAL_LINK: null,
              },
            ],
          },
          {
            LABEL: 'Modal',
            LAYOUT: null,
            PAGE_KEY: null,
            EXTERNAL_LINK: null,
            CHILD: [
              {
                LABEL: 'Modal Control Sample',
                LAYOUT: 'example',
                PAGE_KEY: 'modal',
                EXTERNAL_LINK: null,
              },
              {
                LABEL: '레이어 팝업',
                LAYOUT: 'example',
                PAGE_KEY: 'layerpop',
                EXTERNAL_LINK: null,
              },
              {
                LABEL: 'Alert 또는 Confirm',
                LAYOUT: 'example',
                PAGE_KEY: 'alert',
                EXTERNAL_LINK: null,
              },
              {
                LABEL: '바텀시트',
                LAYOUT: 'example',
                PAGE_KEY: 'bottom_sheet',
                EXTERNAL_LINK: null,
              },
            ],
          },
        ],
      },
      {
        LABEL: '라이브러리 샘플링',
        LAYOUT: null,
        PAGE_KEY: null,
        EXTERNAL_LINK: null,
        CHILD: [
          {
            LABEL: 'Swiperjs',
            LAYOUT: null,
            PAGE_KEY: 'swiper',
            EXTERNAL_LINK: null,
          },
          {
            LABEL: 'AOS',
            LAYOUT: null,
            PAGE_KEY: 'aos',
            EXTERNAL_LINK: null,
          },
          {
            LABEL: 'Plyr',
            LAYOUT: null,
            PAGE_KEY: 'plyr',
            EXTERNAL_LINK: null,
          },
          {
            LABEL: 'AutoComplete.js',
            LAYOUT: null,
            PAGE_KEY: 'auto_complete',
            EXTERNAL_LINK: null,
          },
          {
            LABEL: 'Particles.js',
            LAYOUT: null,
            PAGE_KEY: 'particles',
            EXTERNAL_LINK: null,
          },
          {
            LABEL: 'SortableJS',
            LAYOUT: null,
            PAGE_KEY: 'sortablejs',
            EXTERNAL_LINK: null,
          },
          {
            LABEL: 'Flatpickr',
            LAYOUT: null,
            PAGE_KEY: 'flatpickr',
            EXTERNAL_LINK: null,
          },
          {
            LABEL: 'FontAwesome',
            LAYOUT: null,
            PAGE_KEY: 'fontawesome',
            EXTERNAL_LINK: null,
          },
        ],
      },
    ],
  },
  {
    LABEL: '라이브러리 공식 홈페이지',
    LAYOUT: null,
    PAGE_KEY: null,
    EXTERNAL_LINK: null,
    CHILD: [
      {
        LABEL: 'UAParser.js - OS 및 브라우져 확인',
        LAYOUT: null,
        PAGE_KEY: null,
        EXTERNAL_LINK: 'https://uaparser.js.org/',
      },
      {
        LABEL: 'Swiper - 슬라이드',
        LAYOUT: null,
        PAGE_KEY: null,
        EXTERNAL_LINK: 'https://swiperjs.com/',
      },
      {
        LABEL: 'AOS - 스크롤 반응 애니메이션',
        LAYOUT: null,
        PAGE_KEY: null,
        EXTERNAL_LINK: 'http://michalsnik.github.io/aos/',
      },
      {
        LABEL: 'Plyr - 비디오 플레이어',
        LAYOUT: null,
        PAGE_KEY: null,
        EXTERNAL_LINK: 'https://plyr.io/',
      },
      {
        LABEL: 'autoComplete.js - 자동완성',
        LAYOUT: null,
        PAGE_KEY: null,
        EXTERNAL_LINK: 'https://tarekraafat.github.io/autoComplete.js/#/',
      },
      {
        LABEL: 'particles.js - 파티클',
        LAYOUT: null,
        PAGE_KEY: null,
        EXTERNAL_LINK: 'https://vincentgarreau.com/particles.js/',
      },
      {
        LABEL: 'SortableJS - 리스트 드래그',
        LAYOUT: null,
        PAGE_KEY: null,
        EXTERNAL_LINK: 'https://sortablejs.github.io/Sortable/',
      },
      {
        LABEL: 'flatpickr - 데이트피커',
        LAYOUT: null,
        PAGE_KEY: null,
        EXTERNAL_LINK: 'https://flatpickr.js.org/',
      },
      {
        LABEL: 'fontawesome - 아이콘',
        LAYOUT: null,
        PAGE_KEY: null,
        EXTERNAL_LINK: 'https://fontawesome.com/download',
      },
    ],
  },
];
